---
- name: Deploy
  hosts: api
  tags:
    - deploy
  vars:
    path: "/root/{{ dir }}"
  tasks:
    - name: Creates directory
      file:
        path: "{{ path }}"
        state: directory
    - name: Copy Docker Compose
      copy:
        src: ./docker-compose.yml
        dest: "{{ path }}/docker-compose.yml"
    - name: Copy .env
      copy:
        src: ./.env
        dest: "{{ path }}/.env.pub"
    - name:
      shell:
        cmd: touch .env && sort -u -t '=' -k 1,1 .env.pub .env > .env.build && mv .env.build .env
        chdir: "{{ path }}"
    - name:
      shell:
        cmd: docker compose pull
        chdir: "{{ path }}"
    - name:
      shell:
        cmd: docker compose up -d
        chdir: "{{ path }}"
