version: '3'

services:
  app:
    image: registry.digitalocean.com/main/matrix-aggregator-front
    ports:
      - "3200:3200"
    env_file:
      - .env
    command: 'node .output/server/index.mjs'

networks:
  default:
    external:
      name: ${NETWORK:-proxy}