name: Nuxt

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_REGISTRY_DOMAIN: registry.digitalocean.com
  USERNAME: root
  HOST: matrix.preciselab.io

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: prepare env
        run: |
          ENV=$(cat << EOF
          # GOOGLE_CLIENT_ID=980557834863-garc39g6lp2ir8hlseppmerels6eeql6.apps.googleusercontent.com
          EOF
          )
          echo "$ENV" > .env
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag registry.digitalocean.com/main/matrix-aggregator-front
      - name: Login to registry
        run: docker login -u ${{ secrets.DOCKER_TOKEN }} -p ${{ secrets.DOCKER_TOKEN }} ${{ env.DOCKER_REGISTRY_DOMAIN }}
      - name: Build the Docker image
        run: docker push registry.digitalocean.com/main/matrix-aggregator-front

  reload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: prepare env
        run: |
          ENV=$(cat << EOF
          VIRTUAL_HOST=matrix.preciselab.io
          LETSENCRYPT_HOST=matrix.preciselab.io
          VIRTUAL_PORT=3400
          NITRO_HOST=0.0.0.0
          NITRO_PORT=3400
          EOF
          )
          echo "$ENV" > .env
      - name: read env
        run: cat .env
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [local]
            127.0.0.1 env=prod
            
            [api]
            matrix.preciselab.io ansible_user=root dir=matrix-aggregator-front
    needs: image